# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

[cmd_duration]
min_time = 1000
show_milliseconds = true
disabled = true

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
truncate_to_repo = false
read_only = " "
disabled = false
truncation_symbol = "~/"

[docker]
symbol = " "
disabled = true

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[git_branch]
symbol = " "
disabled = false

[golang]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = false

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[lua]
disabled = true

[memory_usage]
symbol = " "
disabled = true

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "
disabled = true

[nodejs]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[swift]
symbol = "ﯣ "
disabled = true
